// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	"testing/3-mocks/repository"

	mock "github.com/stretchr/testify/mock"
)

// CommentsRepository is an autogenerated mock type for the CommentsRepository type
type CommentsRepository struct {
	mock.Mock
}

// GetComments provides a mock function with given fields: productID
func (_m *CommentsRepository) GetComments(productID string) ([]repository.Comment, error) {
	ret := _m.Called(productID)

	var r0 []repository.Comment
	if rf, ok := ret.Get(0).(func(string) []repository.Comment); ok {
		r0 = rf(productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Comment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveComment provides a mock function with given fields: comment
func (_m *CommentsRepository) SaveComment(comment repository.Comment) error {
	ret := _m.Called(comment)

	var r0 error
	if rf, ok := ret.Get(0).(func(repository.Comment) error); ok {
		r0 = rf(comment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
